### ISSUE TITLE
Using GZipped DSK (actually .MGT/RAW) locks release into SimCoupe

### ISSUE THREAD

**Issue by dandoore** [stefandrissen/SAM-MOD-player#11]
If I want to copy the release onto Gotek (FlashFloppy) or HxC floppy emulators you have to gunzip it and extract the DSK which is an MGT/RAW dump rather than an EDSK headered image - can it just be made a .MGT RAW dump or an EDSK image?

**Comment by stefandrissen** [comment]
The release is the default .dsk image as produced by [pyz80](https://github.com/simonowen/pyz80).

I've added the ``--nozip`` option and attached the result (manually zipped since .dsk is not an allowed extension for issue comments), does that work for you?

[modplayer.zip](https://github.com/stefandrissen/SAM-MOD-player/files/7507698/modplayer.zip)

**Comment by dandoore** [comment]
Perfect - can it be named .MGT though to appease my OCD?
