### ISSUE TITLE
Small C sources on github

### ISSUE THREAD

**Issue by mkrivos** [stefandrissen/SAM-MOD-player#7]
Hello Stefan,

my name is Marian Krivos (Rumsoft) and I know you from my past sam-coupe era.

Maybe you want to see at my latest github upload - https://github.com/mkrivos/samcoupecode:

There are complete source code for anciet application:
- Small C (C language IDE)
- EDIPRO (full wysiwyg text editor)
- ZEUS (assembler)
- Sam Vision 2

Best regards
Marian

**Comment by stefandrissen** [comment]
Hi Marian!

Always great to see old SAM code making it’s way to GitHub! On worldofsam.org we have the following product pages:

- [SAM C](https://www.worldofsam.org/index.php/products/sam-c)
- [EdiPro](https://www.worldofsam.org/index.php/products/edipro)
- [SAM VISION](https://www.worldofsam.org/index.php/products/sam-vision)

Did you ever release Zeus separately or was it always part of Small C?

I'll add links to your github sources later on so that you can grab the disk images first. When a page with approved disk images is edited, the disk images are not downloadable again until Andrew Collier reapproves them.

Sorry... I still don't speak C :-) I jumped over C from Assembly to some high level nonsense :-)

Kind regards,

Stefan

**Comment by stefandrissen** [comment]
I see @dandoore beat me to updating WoS - thanks.
